### ISSUE TITLE
"/products" PATH - is not showing products cards

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-fastapi-stripe#1]
Hello @barreraalexander 

The `/products` index shows the featured product but the rest of the cards are missing: 

Please take a look. For quick comparison exec the Flask sample in Docker: 

`$ docker-compose up --build` -> `http://localhost:5085`

### FastAPI Layout

![image](https://user-images.githubusercontent.com/51070104/196873172-08e45a9e-ae6c-4ccc-82a4-360634f32c42.png)

### Flask Layout 

![image](https://user-images.githubusercontent.com/51070104/196873440-8382bd1c-30f4-47dd-9757-242301a17a7a.png)

**Comment by barreraalexander** [comment]
Products route has been fixed.

**Comment by app-generator** [comment]
Validated. Closing! 

Ty @barreraalexander
