### ISSUE TITLE
'/products' route - should be ended in / (slash)

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-fastapi-stripe#2]
The index of products should use a route with `/` at the end.

```python
@router.get("/products", status_code=status.HTTP_200_OK) 
 ...
```

**Comment by app-generator** [comment]
Hello @barreraalexander 
Thank you for your work.  

Once you deliver a fix, please update the status here (text only). Our testing team will close it if the patch is validated. 

TY!

**Comment by barreraalexander** [comment]
Duly noted!

**Comment by app-generator** [comment]
Validated. Closing!

ty @barreraalexander
