### ISSUE TITLE
Product Page not accessible 

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-fastapi-stripe#3]
Hello @barreraalexander 

On the products index page, the links provided by the featured product are dead links

> Note: Please mirror all features from Flask. In theory, if the user starts the Flask or FastAPI version using Docker, the behaviour should be identical. 

Ty for taking a look.

![image](https://user-images.githubusercontent.com/51070104/196874806-cdb8a800-7556-4e76-8659-945f20134750.png)

**Comment by barreraalexander** [comment]
Product page is now accessible.

**Comment by app-generator** [comment]
Validated. Closing.

Ty @barreraalexander
