### ISSUE TITLE
Docker file with non-standard name

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-fastapi-stripe#6]
Hello @barreraalexander,

Regarding Docker, two files are provided:

- `docker-compose.yaml` -> OK
- `docker-compose copy.yaml` -> Not ok

Please rename the 2nd docker-compose YAML with a suggestive name.
Also might help to specify on README what exactly does compared to the simple set up. 

Ty!

**Comment by barreraalexander** [comment]
Apologies! This was a test file that I forgot to delete. It has no use and has been deleted.
